apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: grayround
    argocd.argoproj.io/instance: grayweb
  name: graysvc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: grayround
  type: NodePort
status:
  loadBalancer: {}
